### ISSUE TITLE
Remove unnecessary directories.

### ISSUE THREAD

**Issue by gargvk81** [dhruvsinghal007/main#1]
I see that under main trunk there are unnecessary directories created. e.g. batch_processing/BatchProcessing. Remove all such directories.

reorganize all project like:
main/helloworld/Xyz_Demo
main/exercise/diningph/arbitrator1/_
main/exercise/diningph/arbitrator2/*
main/exercise/diningph/chandymisra/*
main/exercise/oddeven/*

**Comment by dhruvesingal** [comment]
Resolved!!!

**Comment by gargvk81** [comment]
Issue still not resolved.
Current (example):
main/hello_world/batch_processing/BatchProcessing
main/hello_world/completion_service/CompletionServiceDemo
main/hello_world/count_down_latch/CountDownLatchDemo
...
...

New/Expected:

main/hello_world/BatchProcessing
main/hello_world/CompletionServiceDemo
main/hello_world/CountDownLatchDemo

**Comment by dhruvesingal** [comment]
Now?

**Comment by dhruvesingal** [comment]
I modified it according to the specified setting

**Comment by gargvk81** [comment]
Still not resolved. Example:
exercise/odd_even/OddEvenDemo

**Comment by dhruvesingal** [comment]
Got it... now?
